### ISSUE TITLE
moveMole() function executing after game over 

### ISSUE THREAD

**Issue by Digital-Coder** [kubowania/whack-a-mole#2]
`if (currentTime === 0) {
    clearInterval(timerId)
    alert('GAME OVER! Your final score is' + result)
  }`
after game over mole is still clickable with result increment and moving. How would you stop that ?

**Comment by codewithnick** [comment]
maybe you could just add a line of code to reload the page

**Comment by Digital-Coder** [comment]
solved it by adding moveMole() to interval and clearing it.
`let moveMole = setInterval(randomSquare, 500)`
```
if(currentTime === 0 ) {
    clearInterval(timerId)
    clearInterval(moveMole)
    alert(`GAME OVER! Your final score is${result}`)
    
  }
```

**Comment by codewithnick** [comment]
great
